name: "Enforcing go mod tidy in PRs Workflow"
on: [pull_request]
jobs:
  go_mod_tidy_job:
    runs-on: ubuntu-latest
    container: rishabhpoddar/supertokens_go_driver_testing
    steps:
      - uses: actions/checkout@v2
      - run: git init && git add --all && git -c user.name='test' -c user.email='test@example.com' commit -m 'init for pr action'
      - run: go mod tidy
      - run: git status
      - run: git status | grep -q 'nothing to commit, working directory clean' && echo "true" || echo "false"