name: "Enforcing go mod tidy in PRs Workflow"
on: [pull_request]
jobs:
  go_mod_tidy_job:
    runs-on: ubuntu-latest
    container: rishabhpoddar/supertokens_go_driver_testing
    steps:
      - uses: actions/checkout@v2
      - run: go mod tidy
      - run: git status | grep -q 'nothing to commit, working tree clean' && exit 0 || exit 1